# Параметры сборки проекта «ACID Wallet»

# Память для Gradle-демона
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX (обязательно для Compose и Room)
android.useAndroidX=true

# Код на Kotlin
kotlin.code.style=official

# Ускорение сборки
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=true

# Более компактный R-класс
android.nonTransitiveRClass=true
